### ISSUE TITLE
Views field rewrite messy

### ISSUE THREAD

**Issue by rokat** [drupalprojects/kalatheme#118]
![capture du 2014-07-20 01 02 31](https://cloud.githubusercontent.com/assets/7518186/3636020/ddfae0e4-0f99-11e4-85b9-ab281a53a425.png)

I have looked into it, the reason is the application of an extra "form-control" css on the container.
Will look where it's applied. Or if it's already patched on v4.

**Comment by rokat** [comment]
``` html
<div id="edit-options-alter-text-wrapper" class="form-control form-wrapper dependent-options" style="">
  <div class="form-item form-type-textarea form-item-options-alter-text form-group">
    <label for="edit-options-alter-text">Text </label>
    <div class="form-textarea-wrapper resizable">
      <textarea rows="5" cols="60" name="options[alter][text]" id="edit-options-alter-text" class="form-control form-textarea">
      </textarea>
    </div>
    <span class="help-block">The text to display for this field. You may include HTML. You may enter data from this view as per the "Replacement patterns" below.</span>
  </div>
</div>
```

**Comment by pirog** [comment]
@rokat where is the _extra_ form-control? The one in edit-options-alter-text-wrapper?

**Comment by rokat** [comment]
@pirog  it is as you said ,in the edit-options-alter-text-wrapper, the wrapper doesn't need the form-control, only the textarea.

I have found a solution. 
In

``` php
function kalatheme_process_input(&$element, &$form_state)
```

 kalatheme_process_input (it adds the form-control to both wrapper & textarea)
Removing textarea from the list of types

And

``` php
function kalatheme_textarea($variables)
```

Adding form-control directly to textarea 
that should do the trick, but requires some regression test, to be sure it didn't hurt something else.

Anyway will do a pull request

**Comment by rokat** [comment]
Added the pull request

**Comment by pirog** [comment]
Great! I just posted some comments on the PR. It looks good but going to ask for a second set of eyes and then merge it in!

thanks so much for your help!

**Comment by shawnholt** [comment]
I updated to dev and this solved the text drop down, but the replacement patterns dropdown does not open.  
If I remove /\* position: relative; */ from form-item form-type-checkbox form-item-options-alter-trim checkbox it seems to work.

This is the code:

<div class="collapsible collapsed form-wrapper dependent-options" id="edit-options-alter-help-wrapper" style="overflow: hidden;"><fieldset class="collapsible collapsed form-wrapper panel panel-default collapse-processed" id="edit-options-alter-help-wrapper"><legend class="panel-heading"><div class="panel-title fieldset-legend"><a class="fieldset-title" href="#"><span class="fieldset-legend-prefix element-invisible">Show</span> Replacement patterns</a><span class="summary"></span></div></legend><div class="panel-body fieldset-wrapper"><p>The following tokens are available for this field. Note that due to rendering order, you cannot use fields that come after this field; if you need a field not listed here, rearrange your fields.
If you would like to have the characters '[' and ']' please use the html entity codes '%5B' or  '%5D' or they will get replaced with empty space.</p><div class="item-list"><fields><li class="first">[id] == CiviCRM Events: Event ID</li>
<li class="last">[event_image_42] == CiviCRM Custom: Event Extension: Event Image</li>
</fields></div></div></fieldset>
</div>
