### ISSUE TITLE
What's new in Kalatheme 4?

### ISSUE THREAD

**Issue by agold2** [drupalprojects/kalatheme#12]
Just learned of the 7.x-4.x branch. Exciting! What's new since Kalatheme 3?

**Comment by bassettsj** [comment]
We're adding in new AJAX autocomplete and progress bars. Integration with font API. Better accessibility. And much more magic :+1:—

**Comment by agold2** [comment]
Nice! 

A few questions that might be separate issues:
- Will these features be added to Kalatheme 3? If not, why?
- Will there be an upgrade path for subthemes of Kalatheme 3 to become subthemes of Kalatheme 4?
- First release of Kalatheme 3 with Bootstrap 3 support was less than 5 months ago. How long do you expect Kalatheme 4 to be maintained before Kalatheme 5 starts?

**Comment by bassettsj** [comment]
- Some of these features will, but other might be easy to apply backwards, so some will not
- Yes there will be
- We haven't planned the roadmap, but if you want to get involved feel free to voice in.

**Comment by pirog** [comment]
@agold2 in the house!

Definitely stay tuned here... We have a new 4.x branch here but its just a placeholder for now. 

Ultimately we are looking to bake in a lot of really cool and advanced tools so that power users can generate their own completely different builds of Kalatheme. The Kalatheme on D.o will be one such version .... so. 

I'd also encourage you to keep tabs on https://drupal.org/project/hotsauce

**Comment by agold2** [comment]
@pirog Very excited to see what you're up to in Hot Sauce! Creating a subtheme as part of the install profile looks like a great approach.

@bassettsj   Yes, I think a roadmap would be very valuable. I'm not sure how I could get involved, but let me know. ASU Webspark includes a subtheme of Kalatheme 3, so I'm interested in making sure that ASU knows what's coming so we can devote resources to making sure the distro is using maintained projects/branches.
