### ISSUE TITLE
Add panelized region between two hard coded regions using one-region approach?

### ISSUE THREAD

**Issue by heatherfarrier** [drupalprojects/kalatheme#187]
We are using Kalatheme with Panopoly and radix layouts. The home page (and some subpages) design calls for a persistent top nav bar, a banner region, main navigation region and the content region. See attached layout for visual explanation. 

![layout](https://cloud.githubusercontent.com/assets/8184593/8919434/2bb5470c-3474-11e5-8da4-286b17595295.jpg)

We want the top nav and main nav regions to remain in code while the banner and content regions are controlled by the page manager. Is there a way to accomplish this using Kalatheme's one-region approach? If so, how can we move the banner region above the main nav region while still allowing site builders to manage the banner content using page manager?

**Comment by pirog** [comment]
Do to this i think you would want to have the main nav hardcoded into the layout for the page It's really not the best way to go about this but not sure of another way.

**Comment by heatherfarrier** [comment]
That's what I thought. I was trying to find a way to continue using one-region because a lot of work has already gone into the existing theme. Unfortunately, we will have to reconsider this approach. If I come up with an alternative solution, I will post back.

**Comment by labboy0276** [comment]
I have done something quasi similar to this with another client.  However, you can only have the Persistent top nav in code (in page.tpl).  then you need to use a custom panel pane to create the other nav.  The problem is, it is too difficult to split out the content at the page.tpl then have the layout template wrap around that.  

There are more alternatives too, like using hook_theme to render the 2nd menu.  Then having that hook pass info into the layout template level.  I could think of a few scenarios where you could use hook_theme and hook_theme_registry_alter to make some magic that could happen with this....

**Comment by heatherfarrier** [comment]
I found this approach: https://gist.github.com/jameswilson/74c2dc3ee2df0efc2a5c

However, it's my understanding that drupal_add_region_content() was not intended to place content in the theme but rather for use during the install and update process.

I will look into using hook_theme and hook_theme_registry_alter.
