### ISSUE TITLE
Remove views style plugins: recommend views_bootstrap

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#33]
@pirog and I were talking about removing the views grid plugin, it has an issue with views 3.7 (issue #21). This would be a breaking change for people using that view in 3.x, so we need to go over this with the community.

**Comment by bassettsj** [comment]
I think a good upgrade path might be offering a micro module that people can use if they built views from that views plugin and make note of it there.

**Comment by bassettsj** [comment]
#17 and #21 would be gone if we took this route.

**Comment by pirog** [comment]
@bassettsj i've "fixed" at least #21 here in 3.x. And #17 doesnt seem to manifest with Views 3.8. Might want to check to see if this is the same in 4.x

Still think it might be better to move to a module in 4.x since it will have hotsauce behind it for dependency installation but if there are no issues with the plugin anymore we could still ship and wrap in some sort of module_exists conditional. this way people can still get the magic if they install standalone, if they install with hotsauce/dependencies then we just dont load it.

**Comment by labboy0276** [comment]
@soniktrooth is this issue still an issue?

**Comment by soniktrooth** [comment]
The issue this one sites as a problem is closed so I think this is too.
