### ISSUE TITLE
Master for all active development / releases added as built packages

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#8]
Would like to use master as our active branch here for any current development release we merge into. This includes all the Gruntfiles, SASS, coffeescript, tests, doc files etc. Then we can create a task that copies the built files to a directory that we commit / tag / release and is consumed by our users. That way we can keep it simple for users _and_ have all the goodness I have been adding to make kalatheme better to maintain.
- [ ] Add a grunt bump for automating the version bumping, tagging and changelog additions.
- [ ] Build (a) task(s) to copy over the tasks to a dist folder.
- [ ] Document how to pull request.

:facepunch:

**Comment by pirog** [comment]
This would be instead of the 4.x branch or are you thinking master is for merging in stuff that happens in both 3.x and 4.x? I want to retire 3.x and move to 4.x as soon as it is ready to go and we have a "stock" kalatheme that we can offer that is outwardly similar to what people would get with the current 3.x so we wont have to be maintaining two separate things for too long. 

That said master has no real context or official usage in the drupal space but that may be a good reason for using it this way.
